@startuml
!ENABLE_ALL_PLANT_ELEMENTS = 1
!theme C4_united from https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/themes
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
title C4 Level 3: Advanced Media Library System - Component Diagram - Account Service
skinparam defaultFontSize 16


' Define colour coding '
UpdateBoundaryStyle($bgColor="#E0B6BD", $fontColor="brown", $borderColor="brown")
AddRelTag("Relationship", $textColor="black", $lineColor="black", $lineStyle="dashed")
AddElementTag("routeHandler", $bgColor="#A9D18E", $fontColor="black", $borderColor="black", $legendText="Route Handler (Node.js/Express.js)")
AddElementTag("controller", $bgColor="#9DC3E6", $fontColor="black", $borderColor="black", $shape=RectangleShape(), $legendText="Controller (Node.js/Express.js)")
AddElementTag("service", $bgColor="#76A3D9", $fontColor="black", $borderColor="black",$shape=RectangleShape(), $legendText="Service (Node.js/Express.js)")
AddElementTag("model", $bgColor="#4F83CB", $fontColor="black", $borderColor="black", $shape=RectangleShape(), $legendText="Model (Node.js/Express.js)")
AddElementTag("repo", $bgColor="#2763BE", $fontColor="black", $borderColor="black", $shape=RectangleShape(), $legendText="Entity (MySQL)")
AddElementTag("database", $bgColor="#0043b0", $fontColor="black", $borderColor="black", $legendText="Database (Azure MySQL)")

Container(routeHandler, "Route Handler", "Node.js/Express.js", "Manages internal routes for services.", $tags="routeHandler")

Container_Boundary(account, "Account Service") {
    Component(usrCtr, "Member Controller", "Node.js/Express.js", "Manages input for Member table.", $tags="controller")
    Component(paymentCtr, "Payment Controller", "Node.js/Express.js", "Manages input for Payment table.", $tags="controller")
    Component(subscriptionCtr, "Subscription Controller", "Node.js/Express.js", "Manages input for Subscription table.", $tags="controller")
    Component(empCtr, "Employee Controller", "Node.js/Express.js", "Manages input for Employee table.", $tags="controller")
    Component(userSubCtr, "MemberSubcription Controller", "Node.js/Express.js", "Manages input for MemberSubscription table.", $tags="controller")

    Component(usrService, "Member Service", "Node.js/Express.js", "Provides account creation, member sign-in and security functionality.", $tags="service")
    Component(paymentService, "Payment Service", "Node.js/Express.js", "Handles management of payment details.", $tags="service")
    Component(subService, "Subscription Service", "Node.js/Express.js", "Handles management of subscriptions.", $tags="service")
    Component(empService, "Employee Service", "Node.js/Express.js", "Provides sign-in and security functionality for employees.", $tags="service")
    Component(usrSubService, "MemberSubscription Service", "Node.js/Express.js", "Handles relations between members, subscriptions and payments.", $tags="service")

    Component(usrModel, "Member Model", "Node.js/Express.js", "Represents the member table.", $tags="model")
    Component(paymentModel, "Payment Model", "Node.js/Express.js", "Represents the payment table.", $tags="model")
    Component(subModel, "Subscription Model", "Node.js/Express.js", "Represents the subscription table.", $tags="model")
    Component(empModel, "Employee Model", "Node.js/Express.js", "Represents the employee table.", $tags="model")
    Component(usrSubModel, "MemberSubscription Model", "Node.js/Express.js", "Represents the member-subscription table.", $tags="model")

    Component(userRepo, "Member DB Handler", "Node.js/Express.js", "Handles SQL statements for member accounts.", $tags="repo")
    Component(subRepo, "Subscription DB Handler", "Node.js/Express.js", "Handles SQL statements for subscription info.", $tags="repo")
    Component(userSubRepo, "MemberSubscription DB Handler", "Node.js/Express.js", "Handles SQL statements for member subscriptions.", $tags="repo")
    Component(employeeRepo, "Employee DB Handler", "Node.js/Express.js", "Handles SQL statements for employee accounts.", $tags="repo")
    Component(paymentRepo, "Payment DB Handler", "Node.js/Express.js", "Handles SQL statements for member payment info.", $tags="repo")
}

ContainerDb(database, "Database", "Azure MySQL", "Stores all tables the system requires e.g. media data, user data, inventory data.", $tags="database")

' Relationships - API Gateway to Controller '
Rel(routeHandler, usrCtr, "Handles API calls for member related functionality", $tags="Relationship")
Rel(routeHandler, paymentCtr, "Handles API calls for payment related functionality", $tags="Relationship")
Rel(routeHandler, subscriptionCtr, "Handles API calls for subscription related functionality", $tags="Relationship")
Rel(routeHandler, empCtr, "Handles API calls for employee related functionality", $tags="Relationship")
Rel(routeHandler, userSubCtr, "Handles API calls for specific member subscription and payment functionality", $tags="Relationship")

' Relationships - Internal - Controller to Service '
Rel(usrCtr, usrService, " ", $tags="Relationship")
Rel(paymentCtr, paymentService, " ", $tags="Relationship")
Rel(subscriptionCtr, subService, " ", $tags="Relationship")
Rel(userSubCtr, usrSubService, " ", $tags="Relationship")
Rel(empCtr, empService, " ", $tags="Relationship")

' Relationships - Internal - Service to Model '
Rel(usrService, usrModel, " ", $tags="Relationship")
Rel(paymentService, paymentModel, " ", $tags="Relationship")
Rel(subService, subModel, " ", $tags="Relationship")
Rel(empService, empModel, " ", $tags="Relationship")
Rel(usrSubService, usrSubModel, " ", $tags="Relationship")

' Relationships - Internal - Model to Repo '
Rel(usrModel, userRepo, " ", $tags="Relationship")
Rel(paymentModel, paymentRepo, " ", $tags="Relationship")
Rel(subModel, subRepo, " ", $tags="Relationship")
Rel(empModel, employeeRepo, " ", $tags="Relationship")
Rel(usrSubModel, userSubRepo, " ", $tags="Relationship")

' Relationships - Internal - Repo to Database '
Rel(userRepo, database, "CRUD operations on Member table", $tags="Relationship")
Rel(subRepo, database, "CRUD operations on Subscription table", $tags="Relationship")
Rel(userSubRepo, database, "CRUD operations on MemberSubscriptions table", $tags="Relationship")
Rel(employeeRepo, database, "CRUD operations on Employee table", $tags="Relationship")
Rel(paymentRepo, database, "CRUD operations on Payment table", $tags="Relationship")

SHOW_LEGEND(true)
@enduml
