const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '.env') });

const FRONTEND_PORT = process.env.FRONTEND_PORT;
const API_GATEWAY_PORT = process.env.API_GATEWAY_PORT;
const ACCOUNT_SERVICE_PORT = process.env.ACCOUNT_SERVICE_PORT;
const NOTIFICATION_SERVICE_PORT = process.env.NOTIFICATION_SERVICE_PORT;
const PROCUREMENT_SERVICE_PORT = process.env.PROCUREMENT_SERVICE_PORT;
const STOREFRONT_SERVICE_PORT = process.env.STOREFRONT_SERVICE_PORT;

// console.log("FRONTEND_PORT:", FRONTEND_PORT);
// console.log("API_GATEWAY_PORT:", API_GATEWAY_PORT);
// console.log("ACCOUNT_SERVICE_PORT:", ACCOUNT_SERVICE_PORT);
// console.log("NOTIFICATION_SERVICE_PORT:", NOTIFICATION_SERVICE_PORT);
// console.log("PROCUREMENT_SERVICE_PORT:", PROCUREMENT_SERVICE_PORT);
// console.log("STOREFRONT_SERVICE_PORT:", STOREFRONT_SERVICE_PORT);

module.exports = {
    FRONTEND_PORT: FRONTEND_PORT,
    FRONTEND_ORIGIN: `http://localhost:${FRONTEND_PORT}`,
    API_GATEWAY_PORT: API_GATEWAY_PORT,
    API_GATEWAY: `http://localhost:${API_GATEWAY_PORT}/api`,
    ACCOUNT_SERVICE_PORT: ACCOUNT_SERVICE_PORT,
    ACCOUNT_SERVICE_API: `http://localhost:${ACCOUNT_SERVICE_PORT}/api`,
    NOTIFICATION_SERVICE_PORT: NOTIFICATION_SERVICE_PORT,
    PROCUREMENT_SERVICE_PORT: PROCUREMENT_SERVICE_PORT,
    STOREFRONT_SERVICE_PORT: STOREFRONT_SERVICE_PORT
};
